# Generated by Django 6.0.3 on 2026-05-13 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0011_fix_visitrequest_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('sale', 'Vente'), ('rental', 'Location')], default='sale', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signed_by_vendeur', 'Signé par le vendeur'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('terms', models.TextField(blank=True, default='')),
                ('pdf_data', models.TextField(blank=True)),
                ('signed_by_vendeur_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by_acquereur_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquereur', models.ForeignKey(db_column='acquereur_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_contracts', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='properties.property')),
                ('vendeur', models.ForeignKey(db_column='vendeur_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales_contracts', to=settings.AUTH_USER_MODEL)),
                ('visit_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='properties.visitrequest')),
            ],
            options={
                'db_table': 'contracts_contract',
                'ordering': ['-created_at'],
            },
        ),
    ]
