# Generated by Django 6.0.3 on 2026-04-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_currency_alter_property_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='wilaya',
            new_name='region',
        ),
    ]
