# Generated by Django 6.0.4 on 2026-04-23 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_add_property_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='properties__status_6c6bfe_idx',
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role__in': ['vendeur', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['verification_status', 'is_published'], name='properties__verific_6ec650_idx'),
        ),
    ]
