# Generated by Django 6.0.4 on 2026-04-24 10:58

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_add_listing_type_consulting_visits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultingrequest',
            old_name='property',
            new_name='related_property',
        ),
        migrations.RenameField(
            model_name='visitrequest',
            old_name='property',
            new_name='related_property',
        ),
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='charges_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_turnkey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='visitrequest',
            unique_together={('related_property', 'client', 'status')},
        ),
    ]
