# Generated by Django 6.0.4 on 2026-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_property_consultingrequest_related_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.SmallIntegerField(default=0),
        ),
    ]
