# Generated by Django 6.0.3 on 2026-05-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
    ]
