# Generated by Django 6.0.3 on 2026-05-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_fix_visitrequest_schema'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitrequest',
            unique_together=set(),
        ),
    ]
