# Generated by Django 6.0.3 on 2026-04-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_application_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wilaya',
            new_name='region',
        ),
    ]
